-- US states reference data. Populated by the seed loader from assets/map.json.
-- Geometry is NOT stored here: the seed reads polygons from the GeoJSON for the
-- point-in-polygon join, and the frontend reads the same file to draw the map.
--
-- Join contract: `name` is `properties.level1` from map.json (e.g. "Alabama"),
-- and it is the key the frontend MUST use to match a GeoJSON feature to its
-- per-state count — NOT properties.name ("Alabama, US.AL") or properties.id
-- ("US_adm1_29"). If names ever drift in formatting, add a stable `code` column
-- (properties.id) and join on that instead.
CREATE TABLE states (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);
