-- One advertising impression: a single ad view from a mobile device.
-- ts is stored in UTC (timestamptz); any local-time view (e.g. hour of day) is
-- a presentation concern converted on the client.
-- state_id is resolved once at ingest (point-in-polygon in the seed loader) and
-- is NULL when the coordinate falls outside every US state polygon.
CREATE TABLE impressions (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id bigint           NOT NULL,
    -- Range CHECKs document the coordinate domain and fail loud on garbage,
    -- matching the loader's fail-loud stance. In-range points outside every US
    -- polygon are still accepted (they get state_id = NULL).
    lat       double precision NOT NULL CHECK (lat BETWEEN -90 AND 90),
    lng       double precision NOT NULL CHECK (lng BETWEEN -180 AND 180),
    ts        timestamptz      NOT NULL,
    state_id  integer          REFERENCES states (id)
);

-- Supports single-state drill-down (WHERE state_id = ?) and keeps parent-side
-- deletes cheap. It does NOT accelerate the all-states choropleth: an unfiltered
-- GROUP BY state_id scans the whole table regardless. At scale that lever is the
-- pre-aggregated rollup in V4__rollups.sql (refreshed once after the seed), which
-- every analytical query reads instead of this table — not this index.
CREATE INDEX idx_impressions_state_id ON impressions (state_id);

-- Backs date-range access: Black Friday windows and any date filtering
-- (WHERE ts >= X AND ts < Y). Per-hour-of-day grouping is a function of ts and
-- would need its own expression index if it ever becomes a hot path.
CREATE INDEX idx_impressions_ts ON impressions (ts);

-- Per-device aggregation ("impressions per device").
CREATE INDEX idx_impressions_device_id ON impressions (device_id);
